var exemplaires = new Map();

exemplaires.set("1", {titre: "Croc vert",epuise: true});
exemplaires.set("2", {titre: "Machine qui rêve",epuise: false});
exemplaires.set("3", {titre: "Astérix chez les Bretons",epuise: true});
exemplaires.set("4", {titre: "Capturez un Marsupilami !",epuise: true});
exemplaires.set("5", {titre: "Le ciel lui tombe sur la tête",epuise: false});
exemplaires.set("6", {titre: "Le gri-gri du Niokolo-Koba",epuise: false});
exemplaires.set("7", {titre: "Obélix et compagnie",epuise: true});
exemplaires.set("8", {titre: "Le mariage de Rahan",epuise: false});
exemplaires.set("9", {titre: "Les chasseurs de foudre",epuise: false});
exemplaires.set("10", {titre: "Trolls dans la brume",epuise: false});
exemplaires.set("11", {titre: "Joe bar team Tome 1",epuise: true});
exemplaires.set("12", {titre: "Joe bar team Tome 4",epuise: false});
exemplaires.set("13", {titre: "La colère de Merlin",epuise: true});
exemplaires.set("14", {titre: "Un, deux... Troy",epuise: true});
exemplaires.set("15", {titre: "Shadow",epuise: false});
exemplaires.set("16", {titre: "La loi du dollar",epuise: false});
exemplaires.set("17", {titre: "Bilbo le Hobbit",epuise: true});
exemplaires.set("18", {titre: "Le cheval de fer",epuise: false});
exemplaires.set("19", {titre: "Astérix et Cléopatre",epuise: true});
exemplaires.set("20", {titre: "Les bijoux de la Castafiore",epuise: false});
exemplaires.set("21", {titre: "Litteul Kévin T8",epuise: true});
exemplaires.set("22", {titre: "Boules de poils",epuise: false});
exemplaires.set("23", {titre: "Panik room",epuise: false});
exemplaires.set("24", {titre: "L'évangile oublié",epuise: true});
exemplaires.set("25", {titre: "Nuit et brouillard",epuise: false});
exemplaires.set("26", {titre: "Retour à Greenfalls",epuise: true});
exemplaires.set("27", {titre: "Le piège des sables",epuise: true});
exemplaires.set("28", {titre: "La galerie des gaffes",epuise: false});
exemplaires.set("29", {titre: "L'or des trolls",epuise: false});
exemplaires.set("30", {titre: "Astérix, le papyrus de César",epuise: true});
